In [1]:
from keras.models import load_model

In [2]:
model = load_model('my_model.h5')

In [4]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 4, 4, 3)           150       
_________________________________________________________________
flatten_3 (Flatten)          (None, 48)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                490       
Total params: 640
Trainable params: 640
Non-trainable params: 0
_________________________________________________________________


In [14]:
conv_weights = model.layers[0].get_weights()[0][:,:,0,:]

In [15]:
conv_bias = model.layers[0].get_weights()[1]

In [16]:
conv_weights.shape

(7, 7, 3)

In [17]:
conv_bias.shape

(3,)

In [18]:
conv_bias

array([1.1398909 , 0.55484563, 0.01986638], dtype=float32)

In [23]:
from tensorflow import keras
import numpy as np

In [24]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
x_test = x_test.astype("float32") / 255
x_test = np.expand_dims(x_test, -1)

In [36]:
img = x_test[:1]

In [37]:
soft = model.predict(img)

In [38]:
soft

array([[1.4855564e-07, 6.7034249e-09, 5.9780859e-07, 2.2041757e-02,
        1.2450319e-07, 3.8080838e-05, 2.5692781e-12, 9.7669059e-01,
        5.5025280e-06, 1.2232459e-03]], dtype=float32)

In [45]:
model.layers[0].call(img)[0][:,:,0]

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1.1398909, 1.1398909, 1.1398909, 1.1398909],
       [0.907946 , 0.7213416, 5.846402 , 1.3352809],
       [1.1398909, 1.8322688, 4.142003 , 1.1398909],
       [1.1398909, 4.2031174, 1.2799225, 1.1398909]], dtype=float32)>

In [39]:
np.argmax(soft)

7

In [40]:
y_test[:1]

array([7], dtype=uint8)

In [66]:
for y in range(0, 28, 7):
    for x in range(0, 28, 7):
        # print(f"{x=}, {y=}")
        wsum = 0
        for i in range(7):
            for j in range(7):
                wsum += img[0, y+i, x+j, 0] * \
                    conv_weights[i, j, 0]
        wsum += conv_bias[0]
        print(wsum)
    print("==")

1.1398909091949463
1.1398909091949463
1.1398909091949463
1.1398909091949463
==
0.907946016639471
0.7213415971491486
5.8464020122773945
1.3352808263152838
==
1.1398909091949463
1.832268837839365
4.142002958949888
1.1398909091949463
==
1.1398909091949463
4.203117133118212
1.279922493326012
1.1398909091949463
==


0.0