In [82]:
from sklearn.neural_network import MLPClassifier, MLPRegressor
import numpy as np

In [83]:
xs = np.array([
    0., 0.,
    0., 1.,
    1., 0.,
    1., 1.
]).reshape(4, 2)

ys = np.array([0., 1., 1., 0.]) #.reshape(4,)

# ys = (ys - np.mean(ys)) / np.std(ys)

In [84]:
xs

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [85]:
ys

array([0., 1., 1., 0.])

In [152]:
model = MLPRegressor(activation='relu', max_iter=10000, hidden_layer_sizes=(4,4), random_state=1, verbose=True, early_stopping=False, n_iter_no_change=100, batch_size=1)

In [153]:
model = model.fit(xs, ys)

Iteration 1, loss = 0.12843934
Iteration 2, loss = 0.12768771
Iteration 3, loss = 0.12773889
Iteration 4, loss = 0.12754232
Iteration 5, loss = 0.12750285
Iteration 6, loss = 0.12746590
Iteration 7, loss = 0.12739870
Iteration 8, loss = 0.12735286
Iteration 9, loss = 0.12725038
Iteration 10, loss = 0.12735942
Iteration 11, loss = 0.12723274
Iteration 12, loss = 0.12704889
Iteration 13, loss = 0.12700131
Iteration 14, loss = 0.12693676
Iteration 15, loss = 0.12686686
Iteration 16, loss = 0.12682526
Iteration 17, loss = 0.12685195
Iteration 18, loss = 0.12674329
Iteration 19, loss = 0.12661834
Iteration 20, loss = 0.12656897
Iteration 21, loss = 0.12663178
Iteration 22, loss = 0.12641506
Iteration 23, loss = 0.12634565
Iteration 24, loss = 0.12632158
Iteration 25, loss = 0.12626459
Iteration 26, loss = 0.12623362
Iteration 27, loss = 0.12614061
Iteration 28, loss = 0.12609184
Iteration 29, loss = 0.12614058
Iteration 30, loss = 0.12594997
Iteration 31, loss = 0.12588772
Iteration 32, los

In [154]:
model.predict(xs)

array([ 0.07925489,  0.96711517,  1.00003837, -0.00385179])

In [155]:
print('score:', model.score(xs, ys)) # outputs 0.5
print('predictions:', model.predict(xs)) # outputs [0, 0, 0, 0]
print('expected:', np.array([0, 1, 1, 0]))

score: 0.9926224133721674
predictions: [ 0.07925489  0.96711517  1.00003837 -0.00385179]
expected: [0 1 1 0]


In [156]:
model.coefs_

[array([[-2.98506281e-104,  1.32974640e+000, -4.88344819e-014,
         -1.14752118e+000],
        [-1.85865121e-028, -1.40772356e+000,  9.04573227e-037,
          1.04930294e+000]]),
 array([[ 1.97647357e-050,  4.86886809e-034, -1.64510311e-020,
         -8.77519664e-083],
        [ 1.28414940e-107,  1.37340420e+000,  3.12454700e-037,
         -4.88486742e-049],
        [ 3.83898551e-049,  6.80950777e-021,  1.33178064e-077,
          5.50951051e-076],
        [ 3.51591740e-034,  1.45405995e+000, -3.48279081e-027,
         -1.43634840e-021]]),
 array([[ 5.97207252e-14],
        [ 5.81917512e-01],
        [ 3.82010564e-63],
        [-6.60896067e-65]])]

In [157]:
model.intercepts_

[array([-0.20646505, -0.06404713, -0.16161097,  0.10727908]),
 array([-0.57187049,  0.03638505, -0.69568369, -0.1366456 ]),
 array([-0.03269165])]

In [159]:
model.coefs_[0].shape[0]

2