In [1]:
import sklearn
from sklearn.datasets import load_digits
from sklearn.neural_network import MLPClassifier, MLPRegressor
import numpy as np

In [2]:
digits = load_digits()

In [3]:
digits.data.shape

(1797, 64)

In [4]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [5]:
hot = np.zeros((digits.target.size, 10))

In [6]:
hot[np.arange(digits.target.size), digits.target] = 1.

In [7]:
hot

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [8]:
digits.target[:20]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
model = MLPRegressor(activation='relu', max_iter=10000, hidden_layer_sizes=(64), random_state=1, verbose=True, early_stopping=False, n_iter_no_change=10, batch_size=1)

In [10]:
model.fit(digits.data, hot)

Iteration 1, loss = 0.78753693
Iteration 2, loss = 0.08525289
Iteration 3, loss = 0.04568791
Iteration 4, loss = 0.04045165
Iteration 5, loss = 0.03559797
Iteration 6, loss = 0.03070533
Iteration 7, loss = 0.02417221
Iteration 8, loss = 0.01920049
Iteration 9, loss = 0.01452304
Iteration 10, loss = 0.01055052
Iteration 11, loss = 0.00870267
Iteration 12, loss = 0.00749025
Iteration 13, loss = 0.00676223
Iteration 14, loss = 0.00629670
Iteration 15, loss = 0.00603007
Iteration 16, loss = 0.00579950
Iteration 17, loss = 0.00571990


C:\Users\maxim\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:587: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


MLPRegressor(batch_size=1, hidden_layer_sizes=64, max_iter=10000,
             random_state=1, verbose=True)

In [ ]:
print('score:', model.score(digits.data, hot)) # outputs 0.5
print('predictions:', model.predict(digits.data)) # outputs [0, 0, 0, 0]

score: 0.9294123665358287
predictions: [[ 1.12157867 -0.02534026 -0.01555669 ... -0.01260276 -0.04838875
  -0.0128105 ]
 [ 0.00693085  1.15180134  0.00149356 ... -0.00397182 -0.08875125
   0.01958835]
 [ 0.00850464  0.11547039  0.87810075 ...  0.00191159  0.06193763
  -0.0015622 ]
 ...
 [ 0.0208159   0.03745727 -0.00326677 ... -0.0079551   0.98548496
   0.00760908]
 [-0.02874952 -0.04279712 -0.02221592 ... -0.02249915 -0.03085049
   1.28487721]
 [ 0.02375508  0.07059453  0.0312122  ...  0.02543246  0.69487673
   0.05206427]]


In [ ]:
from tinbasic import mlpreg_tibasic

In [ ]:
out = mlpreg_tibasic(model, "formula")

In [ ]:
model.predict(digits.data[2:2+1])

array([[ 0.00850464,  0.11547039,  0.87810075, -0.00895401, -0.00920414,
        -0.00159965,  0.00689971,  0.00191159,  0.06193763, -0.0015622 ]])

In [ ]:
f"{{{','.join(map(lambda x: str(x), digits.data[2]))}->L1"

'{0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,3.0,16.0,15.0,14.0,0.0,0.0,0.0,0.0,8.0,13.0,8.0,16.0,0.0,0.0,0.0,0.0,1.0,6.0,15.0,11.0,0.0,0.0,0.0,1.0,8.0,13.0,15.0,1.0,0.0,0.0,0.0,9.0,16.0,16.0,5.0,0.0,0.0,0.0,0.0,3.0,13.0,16.0,16.0,11.0,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0->L1'

In [ ]:
print(out)

max(0,{L1(2)*(0-.141)+L1(3)*(0-.053)+L1(4)*(0-.033)+L1(5)*(0-.059)+L1(6)*(0-.023)+L1(7)*(0-.386)+L1(8)*(0-.09)+L1(9)*.083+L1(10)*.005+L1(11)*.16+L1(12)*.008+L1(13)*.115+L1(14)*.004+L1(15)*(0-.051)+L1(16)*(0-.141)+L1(17)*(0-.006)+L1(18)*(0-.008)+L1(19)*.007+L1(20)*(0-.094)+L1(21)*.065+L1(22)*(0-.016)+L1(23)*.208+L1(25)*(0-.017)+L1(26)*(0-.036)+L1(27)*(0-.272)+L1(28)*(0-.305)+L1(29)*(0-.18)+L1(30)*.083+L1(31)*.145+L1(34)*(0-.559)+L1(35)*(0-.295)+L1(36)*(0-.043)+L1(37)*(0-.148)+L1(38)*(0-.119)+L1(39)*(0-.95)+L1(42)*.203+L1(43)*.187+L1(44)*.116+L1(45)*(0-.169)+L1(46)*(0-.248)+L1(47)*(0-.006)+L1(48)*.063+L1(49)*.063+L1(50)*.164+L1(51)*(0-.08)+L1(52)*.28+L1(53)*.147+L1(54)*.18+L1(55)*.063+L1(56)*.064+L1(57)*.035+L1(58)*.194+L1(59)*(0-.032)+L1(60)*.205+L1(61)*(0-.061)+L1(62)*.156+L1(63)*.086+L1(64)*.115+0.043,L1(4)*(0-.019)+L1(5)*(0-.021)+L1(6)*.004+L1(7)*.004+L1(11)*(0-.013)+L1(12)*(0-.02)+L1(13)*(0-.015)+L1(14)*.006+L1(15)*.002+L1(19)*(0-.019)+L1(20)*(0-.017)+L1(21)*.003+L1(22)*.009+L1(23)*

In [ ]:
np.max(digits.data)

16.0