In [1]:
from sklearn.neural_network import MLPClassifier, MLPRegressor
import numpy as np

In [2]:
xs = np.array([
    0., 0.,
    0., 1.,
    1., 0.,
    1., 1.
]).reshape(4, 2)

ys = np.array([0., 1., 1., 0.]) #.reshape(4,)

# ys = (ys - np.mean(ys)) / np.std(ys)

In [3]:
xs

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [4]:
ys

array([0., 1., 1., 0.])

In [5]:
model = MLPRegressor(activation='relu', max_iter=10000, hidden_layer_sizes=(16,16), random_state=1, verbose=True, early_stopping=False, n_iter_no_change=100, batch_size=1)

In [6]:
model = model.fit(xs, ys)

Iteration 1, loss = 0.82758542
Iteration 2, loss = 0.78280590
Iteration 3, loss = 0.73179013
Iteration 4, loss = 0.68773097
Iteration 5, loss = 0.64935881
Iteration 6, loss = 0.60940846
Iteration 7, loss = 0.58017629
Iteration 8, loss = 0.54799949
Iteration 9, loss = 0.51092306
Iteration 10, loss = 0.48130181
Iteration 11, loss = 0.45389832
Iteration 12, loss = 0.42405886
Iteration 13, loss = 0.40453332
Iteration 14, loss = 0.38306742
Iteration 15, loss = 0.36279096
Iteration 16, loss = 0.34101246
Iteration 17, loss = 0.33143932
Iteration 18, loss = 0.30916757
Iteration 19, loss = 0.29529887
Iteration 20, loss = 0.27969379
Iteration 21, loss = 0.26833650
Iteration 22, loss = 0.25369780
Iteration 23, loss = 0.23826733
Iteration 24, loss = 0.23089505
Iteration 25, loss = 0.22135578
Iteration 26, loss = 0.21220122
Iteration 27, loss = 0.20022281
Iteration 28, loss = 0.19458160
Iteration 29, loss = 0.18806167
Iteration 30, loss = 0.18360650
Iteration 31, loss = 0.17354783
Iteration 32, los

In [7]:
model.predict(xs)

array([0.0010646 , 0.99781347, 0.99884986, 0.00216278])

In [8]:
print('score:', model.score(xs, ys)) # outputs 0.5
print('predictions:', model.predict(xs)) # outputs [0, 0, 0, 0]
print('expected:', np.array([0, 1, 1, 0]))

score: 0.9999880852655716
predictions: [0.0010646  0.99781347 0.99884986 0.00216278]
expected: [0 1 1 0]


In [9]:
model.coefs_

[array([[-3.25373800e-01,  3.55797566e-01, -5.35381004e-01,
         -2.84813673e-15, -2.24395637e-01, -4.20713188e-01,
         -8.03305298e-07, -2.60566409e-01, -2.98997627e-02,
          5.47610312e-02,  2.99633365e-35,  4.09367955e-01,
         -1.82557543e-07,  5.60287782e-01, -6.73172712e-01,
          5.96045632e-21],
        [-4.56696746e-02,  1.03953469e-01,  3.21682315e-01,
         -3.15492676e-07,  3.16188902e-01,  5.56658112e-01,
          3.32269347e-18,  2.44507722e-01,  5.22606252e-01,
          3.39281214e-01, -1.37713623e-04, -8.42355176e-01,
         -2.51120709e-06,  3.88000830e-01, -6.73172682e-01,
         -1.60991085e-35]]),
 array([[-3.51708096e-23, -1.62769776e-01, -1.41540600e-05,
          5.22984302e-02, -7.04804721e-02, -2.57198144e-20,
         -1.37154281e-01, -2.37707779e-01,  2.30313416e-01,
         -7.32893802e-09,  9.21428596e-37,  3.16984008e-01,
         -3.88416590e-01, -2.51895347e-36,  1.28016296e-25,
         -8.20980778e-02],
        [-3.97965

In [10]:
model.intercepts_

[array([ 0.52066008, -0.09417066,  0.21362481, -0.2130242 ,  0.24053761,
         0.33548159, -0.55623279,  0.42209894,  0.57994716,  0.34176399,
        -0.25352144,  0.4329726 , -0.45815514,  0.01946621,  0.67321439,
        -0.23831385]),
 array([-0.29360735,  0.13340547, -0.13408494, -0.30687235,  0.21265764,
        -0.16257909,  0.26636635,  0.46399497, -0.08385267, -0.33697802,
        -0.26590207,  0.10512076,  0.19207277, -0.25271103, -0.21820934,
         0.26684657]),
 array([-0.10957755])]

In [11]:
model.coefs_[0].shape[0]

2

In [12]:
import tinbasic

In [13]:
out = tinbasic.mlpreg_tibasic(model, "formula")

In [14]:
print(out)

max(0,{L1(1)*(0-.325)+L1(2)*(0-.046)+0.521,L1(1)*.356+L1(2)*.104-0.094,L1(1)*(0-.535)+L1(2)*.322+0.214,L1(1)*(0-.224)+L1(2)*.316+0.241,L1(1)*(0-.421)+L1(2)*.557+0.335,L1(1)*(0-.261)+L1(2)*.245+0.422,L1(1)*(0-.03)+L1(2)*.523+0.58,L1(1)*.055+L1(2)*.339+0.342,L1(1)*.409+L1(2)*(0-.842)+0.433,L1(1)*.56+L1(2)*.388+0.019,L1(1)*(0-.673)+L1(2)*(0-.673)+0.673->L1
max(0,{L1(1)*(0-.163)+L1(2)*.155+L1(3)*(0-.19)+L1(4)*(0-.353)+L1(5)*(0-.515)+L1(6)*.009+L1(7)*(0-.164)+L1(8)*.258+L1(9)*.81+L1(10)*.183+L1(11)*(0-.151)+0.133,L1(1)*.052+L1(2)*.165+L1(3)*(0-.384)+L1(4)*.098+L1(5)*.292+L1(6)*.196+L1(7)*(0-.172)+L1(8)*.333+L1(9)*.155+L1(10)*.122+L1(11)*.329-0.307,L1(1)*(0-.07)+L1(2)*.182+L1(3)*.037+L1(4)*.427+L1(5)*.231+L1(6)*(0-.141)+L1(7)*.225+L1(8)*(0-.33)+L1(9)*.603+L1(10)*.205+L1(11)*(0-.448)+0.213,L1(1)*(0-.137)+L1(2)*.465+L1(3)*(0-.335)+L1(4)*.059+L1(5)*.144+L1(6)*(0-.477)+L1(7)*.143+L1(8)*.046+L1(9)*(0-.233)+L1(10)*.239+L1(11)*.054+0.266,L1(1)*(0-.238)+L1(2)*(0-.453)+L1(3)*.633+L1(4)*(0-.131)+L1(5)

In [16]:
print(tinbasic.nn_formula_write_archived(model.coefs_[0],model.intercepts_[0]))

UnArchive L2
{L2(1)*(0-.325)+0.521,L2(1)*.356-0.094,L2(1)*(0-.535)+0.214,0,L2(1)*(0-.224)+0.241,L2(1)*(0-.421)+0.335,0,L2(1)*(0-.261)+0.422,L2(1)*(0-.03)+0.58,L2(1)*.055+0.342,0,L2(1)*.409+0.433,0,L2(1)*.56+0.019,L2(1)*(0-.673)+0.673,0,->L1
ClrList L2
UnArchive L3
L3(1)*(0-.046)+L1(1)->L1(1)
L3(1)*.104+L1(2)->L1(2)
L3(1)*.322+L1(3)->L1(3)
L3(1)*.316+L1(5)->L1(5)
L3(1)*.557+L1(6)->L1(6)
L3(1)*.245+L1(8)->L1(8)
L3(1)*.523+L1(9)->L1(9)
L3(1)*.339+L1(10)->L1(10)
L3(1)*(0-.842)+L1(12)->L1(12)
L3(1)*.388+L1(14)->L1(14)
L3(1)*(0-.673)+L1(15)->L1(15)


In [20]:
out = tinbasic.nn_formula_write_archived(model.coefs_[0],model.intercepts_[0]) + "\n"

In [21]:
out += tinbasic.nn_formula_simplify(model.coefs_[1:],model.intercepts_[1:])

In [22]:
print(out)

UnArchive L2
{L2(1)*(0-.325)+0.521,L2(1)*.356-0.094,L2(1)*(0-.535)+0.214,0,L2(1)*(0-.224)+0.241,L2(1)*(0-.421)+0.335,0,L2(1)*(0-.261)+0.422,L2(1)*(0-.03)+0.58,L2(1)*.055+0.342,0,L2(1)*.409+0.433,0,L2(1)*.56+0.019,L2(1)*(0-.673)+0.673,0,->L1
ClrList L2
UnArchive L3
L3(1)*(0-.046)+L1(1)->L1(1)
L3(1)*.104+L1(2)->L1(2)
L3(1)*.322+L1(3)->L1(3)
L3(1)*.316+L1(5)->L1(5)
L3(1)*.557+L1(6)->L1(6)
L3(1)*.245+L1(8)->L1(8)
L3(1)*.523+L1(9)->L1(9)
L3(1)*.339+L1(10)->L1(10)
L3(1)*(0-.842)+L1(12)->L1(12)
L3(1)*.388+L1(14)->L1(14)
L3(1)*(0-.673)+L1(15)->L1(15)max(0,{L1(1)*(0-.163)+L1(2)*.155+L1(3)*(0-.19)+L1(5)*(0-.353)+L1(6)*(0-.515)+L1(8)*.009+L1(9)*(0-.164)+L1(10)*.258+L1(12)*.81+L1(14)*.183+L1(15)*(0-.151)+0.133,L1(1)*.052+L1(2)*.165+L1(3)*(0-.384)+L1(5)*.098+L1(6)*.292+L1(8)*.196+L1(9)*(0-.172)+L1(10)*.333+L1(12)*.155+L1(14)*.122+L1(15)*.329-0.307,L1(1)*(0-.07)+L1(2)*.182+L1(3)*.037+L1(5)*.427+L1(6)*.231+L1(8)*(0-.141)+L1(9)*.225+L1(10)*(0-.33)+L1(12)*.603+L1(14)*.205+L1(15)*(0-.448)+0.213,L1(1)*(0